project:
  type: website
  output-dir: docs

website:
  title: "data_sherlock"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Blogs
    tools:
      - icon: twitter
        href: https://twitter.com/mukeshmahendran
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/MUKESHRAJMAHENDRAN/datasherlock
          - text: Report a Bug
            url:  https://github.com/MUKESHRAJMAHENDRAN/datasherlock/issues

format:
  html:
    theme: yeti
    css: styles.css
    toc: true


