project:
  type: website
  output-dir: docs

website:
  title: "dataSherlock"
  navbar:
    right:
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/MUKESHRAJMAHENDRAN
      - icon: twitter
        href: https://x.com/mukeshmahendran
format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    mermaid:
      theme: neutral



